name: pytest-ws-replay
#  github 流水线文件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest_test:
    runs-on: ubuntu-latest
    container: python:3.9  
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m pytest tests/unit/ -v
